# Generated by Django 3.1.5 on 2021-02-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiTemp',
        ),
        migrations.DeleteModel(
            name='IdeList202032020ReadyToUploadOffice',
        ),
        migrations.DeleteModel(
            name='PropertyMasterApiMongo',
        ),
    ]
